# Input file autogenerated from init file init.cu                                               
VERS    LM:7 FP:7
IO      SHOW=f HELP=f WKP=F IACTIV=f VERBOS=31
% const pwmode=0 pwemax=3
HAM     AUTOBAS[PNU=1 LOC=1 LMTO=3 MTO=1 GW=0]  GMAX=4.1
        PWMODE={pwmode} PWEMIN=0 PWEMAX={pwemax} OVEPS=0
        ELIND=-.7
% const nit=1
ITER    MIX=B2,b=.3  NIT={nit}  CONVC=1e-5
% const met=5 nk=0
BZ      NKABC={nk}  METAL={met}
#SYMGRP i*i i*r3(-1,1,1) r4z
STRUC 
  NSPEC=1  NBAS=1  NL=5
  ALAT=6.7973476  PLAT= 0.5  0.5  0  0.5  0  0.5  0  0.5  0.5
SPEC 
  ATOM=Cu         Z= 29  R= 2.403225  LMX=2  LMXA=4
SITE 
  ATOM=Cu         POS=  0.0000000   0.0000000   0.0000000
